ameliotation robot framework report

diff --git a/.github/workflows/robot-tests.yml b/.github/workflows/robot-tests.yml
--- a/.github/workflows/robot-tests.yml
+++ b/.github/workflows/robot-tests.yml
@@ -98,7 +98,7 @@ jobs:
       if: failure()
       run: |
         if [ -f "Results/output.xml" ]; then
-          cat Results/output.xml | grep -i failure || echo "No failures found in output.xml"
+          cat Results/output.xml | grep -i failures || echo "No failures found in output.xml"
         else
           echo "No output.xml file found"
         fi
@@ -119,8 +119,8 @@ jobs:
         check_name: "Robot Framework Test Results"
         
     - name: Robot Framework Report
+      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
       uses: joonvena/robotframework-reporter-action@v2.4
-      if: always()
       with:
         gh_access_token: ${{ secrets.GITHUB_TOKEN }}
         report_path: Results
@@ -128,7 +128,7 @@ jobs:
     - name: Fail workflow if tests failed
       if: always()
       run: |
-        if grep -q '<failure' Results/output.xml; then
+        if grep -q '<failures' Results/output.xml; then
            echo "❌ Tests failed, marking the job as failed."
            exit 1
         else
